export const ENGINE_CONSTANTS = Object.freeze({
  ENGINE_VERSION: "kts-i1.0.0",
  RULESET_VERSION: "kts-foundation-0.1",

  TICKS_PER_SECOND: 60,
  WORLD_MIN: 0,
  WORLD_MAX: 1_000_000,

  PLAYER_START_X: 500_000,
  PLAYER_START_Y: 800_000,
  PLAYER_RADIUS: 18_000,
  PLAYER_ACCELERATION_PER_TICK: 360,
  PLAYER_DIAGONAL_ACCELERATION_PER_TICK: 255,
  PLAYER_DRAG_PER_TICK: 220,
  PLAYER_MAX_SPEED_PER_TICK: 7_000,

  PROJECTILE_RADIUS: 4_000,
  PROJECTILE_SPEED_PER_TICK: 11_000,
  PROJECTILE_LIFETIME_TICKS: 90,
  MAX_ACTIVE_PROJECTILES: 64,

  TOTAL_POWER: 100,
  MIN_CHANNEL_POWER: 10,
  MAX_CHANNEL_POWER: 70,
  POWER_SHIFT_INCREMENT: 5,
  POWER_SHIFT_COOLDOWN_TICKS: 12,

  INITIAL_WEAPONS_POWER: 34,
  INITIAL_DEFENCE_POWER: 33,
  INITIAL_SIGNAL_POWER: 33,

  MAX_DEFENCE_INTEGRITY: 10_000,
  MAX_SIGNAL_INTEGRITY: 10_000,

  RECOVERY_PULSE_COOLDOWN_TICKS: 900,
  RECOVERY_PULSE_SIGNAL_RESTORE: 1_200,
  RECOVERY_PULSE_DEFENCE_RESTORE: 600,

  SIGNAL_RECOVERY_DELAY_TICKS: 90,
  DEFENCE_RECOVERY_DELAY_TICKS: 120,
  SIGNAL_COLLAPSE_GRACE_TICKS: 180,
} as const);

export type EngineConstants = typeof ENGINE_CONSTANTS;
